global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "checkbox-backend"
    static_configs:
      - targets: ["app:8080"]
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
