{
 "title": "Checkboxes Backend Monitoring dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP REQUESTS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{method!=\"OPTIONS\", endpoint!=\"/metrics\"}",
     "legendFormat": "{{method}} - {{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Active WebSocket Connections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "websocket_connections_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Grid Updates",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "grid_state_updates_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Websocket Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "rate(websocket_messages_total[5m])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))* 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}